name: Web PR Check

permissions:
  contents: read
  pull-requests: write

on:
  push:
    paths:
      - "client/frontend/**"
      - ".github/workflows/pr-check-web.yml"
  pull_request:
    paths:
      - "client/frontend/**"
      - ".github/workflows/pr-check-web.yml"

jobs:
  frontend:
    runs-on: ubuntu-latest

    env:
      ROOM_ID_PREFIX: fake_room_id_prefix
      E2EE_WIRE_PREFIX: fake_e2ee_wire_prefix
      WEBRTC_FILE_CHANNEL_LABEL: fake_webrtc_file_channel_label
      USE_LOCAL_TLS: false
      
    defaults:
      run:
        working-directory: client/frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: "latest"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "pnpm"
          cache-dependency-path: client/frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format check
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: Check dist exists
        run: |
          if [ ! -d "dist" ]; then
            echo "‚ùå dist folder not found"
            exit 1
          fi
