name: Server PR Check

permissions:
  contents: read
  pull-requests: write

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/pr-check-server.yml"

  pull_request:
    paths:
      - "server/**"
      - ".github/workflows/pr-check-server.yml"

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.7"
          cache: true
          cache-dependency-path: server/go.sum

      - name: Download dependencies
        run: go mod download

      - name: Go Vet
        run: go vet ./...

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2025.1.1

      - name: Staticcheck
        run: staticcheck ./...

      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Gosec
        run: gosec ./...

      - name: Install Govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Govulncheck
        run: govulncheck ./...

      - name: Create bin directory if it doesn't exist
        run: mkdir -p bin

      - name: Build
        run: go build -o bin/server ./cmd/api/main.go

      - name: Check if the server binary was created
        run: |
          if [ -f "bin/server" ]; then
            echo "Server binary created successfully."
          else
            echo "Error: Server binary not found!"
            exit 1
          fi

      - name: Test
        run: go test $(go list ./... | grep -v /cmd/)

      - name: Test Race
        run: go test --race $(go list ./... | grep -v /cmd/)
