name: Desktop PR Check

permissions:
  contents: read
  pull-requests: write

on:
  push:
    paths:
      - "client/web-desktop/**"
      - ".github/workflows/pr-check-desktop.yml"

  pull_request:
    paths:
      - "client/web-desktop/**"
      - ".github/workflows/pr-check-desktop.yml"

jobs:
  desktop:
    runs-on: ubuntu-latest

    env:
      ROOM_ID_PREFIX: fake_room_id_prefix
      E2EE_WIRE_PREFIX: fake_e2ee_wire_prefix
      WEBRTC_FILE_CHANNEL_LABEL: fake_webrtc_file_channel_label
      USE_LOCAL_TLS: false

    defaults:
      run:
        working-directory: client/web-desktop

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: "latest"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "pnpm"
          cache-dependency-path: client/web-desktop/frontend/pnpm-lock.yaml

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true
          cache-dependency-path: client/web-desktop/go.sum

      - name: Install frontend dependencies and build
        run: cd frontend && pnpm install && pnpm build && cd ..

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: go test ./...

      - name: Test Race
        run: go test --race ./...
